project:
  type: website
  resources: 
    - ".well-known/atproto-did"
    - "assets/*"
    - "assets/2025-04-01-gemini-2-5-pro/viewer/logs"
    - "assets/2025-04-15-gpt-4-1/viewer/logs"
    - "assets/2025-04-18-o3-o4-mini/viewer/logs"
    - "assets/2025-05-07-gemini-2-5-pro-new/viewer/logs"
    - "assets/2025-05-21-gemini-2-5-flash/viewer/logs"
  post-render: 
    - "cp -rv static/. _site" # source: https://github.com/quarto-dev/quarto-cli/discussions/4162#discussioncomment-4831352

website:
  title: "Simon P. Couch"
  site-url: https://simonpcouch.com
  description: "Building tools for data scientists at Posit (née RStudio)."
  favicon: assets/cabin.png
  page-navigation: true
  back-to-top-navigation: true
  google-analytics: "G-DDB8R0B1ZW"
  comments: 
    utterances:
      repo: "simonpcouch/website"
      theme: "github-light"
  navbar:
    logo: assets/cabin.png
    tools:
    - icon: github
      href: https://www.github.com/simonpcouch/website
    right:
      - text: About
        aria-label: "About Me"
        href: about/index.qmd
      - text: Blog
        aria-label: "Some Pitter Patters With R"
        href: blog/index.qmd
      - text: Software
        aria-label: "Software"
        href: software.qmd
  
  page-footer:  
    left: >-
     &#169; 2024 Simon P. Couch &#8729; Made with [Quarto](https://quarto.org)

format: 
  html:
    theme:
      - cosmo
      - assets/simon-light.scss
      - assets/simon.scss
    code-link: true
    pagetitle: "{{< meta title >}} | Simon P. Couch"

execute: 
  freeze: true
