[build]
publish = "public"
command = "hugo --gc --minify"
[context.production.environment]
HUGO_VERSION = "0.101.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
publish = "public"
HUGO_VERSION = "0.68.3"
