[context.production]
  command = "python freeze.py"
  publish = "build"
  
[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  publish = "public"
  HUGO_VERSION = "0.68.3"
